org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# metadata
mod_id=schematicanon_processing_pattern
mod_version=0.0
mod_name=Schematicanon Processing Pattern
mod_description=Generate AE2 processing pattern from Create schematicanon.
mod_license=MIT
mod_author=Myitian
mod_source=https://github.com/Myitian/SchematicanonProcessingPattern
maven_group=net.myitian.schematicanon_processing_pattern
mod_version_id=1.21.1
# minecraft
minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# neoforge
neoforge_version=21.1.220
#
# mods
create_version=6.0.9-216
ae2_version=19.2.17