org.gradle.jvmargs=-Xmx4G

mod_id=schematicanon_processing_pattern
mod_version=0.0
mod_name=Schematicanon Processing Pattern
mod_description=Generate AE2 processing pattern from Create schematicanon.
mod_license=MIT
mod_author=example
mod_source=https://example.net/SchematicanonProcessingPattern
mod_icon=pack.png

maven_group=net.myitian.schematicanon_processing_pattern

version_id=1.20
minecraft_version=1.20.1
supported_minecraft_version_fabric=>=1.18.2 <=1.20.1
supported_minecraft_version_forge=[1.18.2,1.20.1]
parchment_mappings=1.20.1:2023.09.03

enabled_platforms=fabric,forge

fabric_loader_version=0.18.4

forge_version=1.20.1-47.4.17

mod_menu_version=7.2.2
fabric_create_version=6.0.8.1+build.1744-mc1.20.1
forge_create_version=mc1.20.1-6.0.8
fabric_ae2_version=kA3rm9EP
forge_ae2_version=15.4.10


fabric_api_version=0.92.7+1.20.1