org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# metadata
mod_id=schematicanon_processing_pattern
mod_version=1.0
mod_name=Schematicanon Processing Pattern
mod_description=Generate AE2 processing pattern from Create schematicanon.
mod_license=MIT
mod_author=Myitian
mod_source=https://github.com/Myitian/SchematicanonProcessingPattern
maven_group=net.myitian.schematicanon_processing_pattern
mod_version_id=1.19.2
# minecraft
minecraft_version=1.19.2
parchment_mappings_version=2022.11.27
enabled_platforms=fabric,forge
# fabric
fabric_loader_version=0.18.4
fabric_api_version=0.77.0+1.19.2
# forge
forge_version=1.19.2-43.5.2
#
# mods
fabric_create_version=0.5.1-i-build.1630+mc1.19.2
forge_create_version=1.19.2-0.5.1.i
fabric_ae2_version=fabric-12.9.9
forge_ae2_version=forge-12.9.9